# Generated by Django 4.2.7 on 2024-12-08 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=50)),
                ('neighbourhood', models.TextField(blank=True, null=True)),
                ('subdivision_number', models.CharField(max_length=50)),
                ('land_use_group', models.CharField(choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
